### ISSUE TITLE
add Err to Error, Errorf, Fatal, Fatalf, Warn, Warnf methods

### ISSUE THREAD

**Issue by shahsavan** [Trendyol/overlog#3]
I need to pass Error to logs, but 
`Error, Errorf, Fatal, Fatalf, Warn, Warnf`
methods don't support Error.
for example:
```
func (o *Overlog) Error(args ...interface{}) {
	o.log.Error().Msg(message("", args...))
}
```
should be changed to:
```
func (o *Overlog) Error(err error, args ...interface{}) {
	o.log.Error().Err(err).Msg(message("", args...))
}
```

**Comment by emrearslan** [comment]
You can actually use it. You can look below or I've updated the [example](https://github.com/Trendyol/overlog/blob/master/overlogger_example_test.go#L105).

````go
if err != nil {
	over.Log().Error(err)
	over.Log().Errorf("Failed to deserialize payload: %s", err)
}
````
